version: '3.8'

services:
  php:
    build: .
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    env_file:
      - ./backend/.env
    restart: always

  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  frontend:
    image: nginx:alpine
    container_name: frontend-container
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - php
    restart: always

volumes:
  db_data:
